name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore SchedentAPI
      
    - name: Build
      run: dotnet build --no-restore SchedentAPI\Schedent.API
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: api-artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: SchedentAPI\Schedent.API\bin

